//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim Slot Elements
// ------------------------------ ---------- ------- ----------- ---- --------
// samShadow                       sampler_c      NA          NA    1        1
// txShadowMap                       texture  float4          2d    2        1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
// POSITION                 0   xyz         1     NONE   float       
// NORMAL                   0   xyz         2     NONE   float       
// TANGENT                  0   xyz         3     NONE   float       
// TEXCOORD                 0   xy          4     NONE   float       
// TEXCOORD                 1   xyzw        5     NONE   float   xyzw
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed | skipOptimization
dcl_sampler s1, mode_comparison
dcl_resource_texture2d (float,float,float,float) t2
dcl_input_ps linear v5.xyzw
dcl_output o0.xyzw
dcl_temps 1
//
// Initial variable locations:
//   v0.x <- input.PosH.x; v0.y <- input.PosH.y; v0.z <- input.PosH.z; v0.w <- input.PosH.w; 
//   v1.x <- input.PosW.x; v1.y <- input.PosW.y; v1.z <- input.PosW.z; 
//   v2.x <- input.NorW.x; v2.y <- input.NorW.y; v2.z <- input.NorW.z; 
//   v3.x <- input.TangentW.x; v3.y <- input.TangentW.y; v3.z <- input.TangentW.z; 
//   v4.x <- input.Tex.x; v4.y <- input.Tex.y; 
//   v5.x <- input.ShadowH.x; v5.y <- input.ShadowH.y; v5.z <- input.ShadowH.z; v5.w <- input.ShadowH.w; 
//   o0.x <- <PS return value>.x; o0.y <- <PS return value>.y; o0.z <- <PS return value>.z; o0.w <- <PS return value>.w
//
#line 139 "D:\Projects\Demo\Demo\SkinDemo\Shaders\DemoShader.hlsl"
nop 
nop 
nop 
nop 
mov r0.xyzw, v5.xyzw

#line 88
div r0.xyz, r0.zxyz, r0.wwww  // r0.x <- shadowPosH.z; r0.y <- shadowPosH.x; r0.z <- shadowPosH.y

#line 91
mov r0.x, r0.x  // r0.x <- depth

#line 111
sample_c_lz_indexable(texture2d)(float,float,float,float) r0.x, r0.yzyy, t2.xxxx, s1, r0.x  // r0.x <- percentLit
mov r0.x, r0.x  // r0.x <- <CalcShadowFactor return value>

#line 140
mov r0.x, r0.x  // r0.x <- PCF

#line 147
nop 

#line 153
nop 

#line 163
itof r0.y, l(100)
mul o0.x, r0.y, r0.x
mov o0.yzw, l(0,0,0,1.000000)
ret 
// Approximately 16 instruction slots used
